spring:
  application:
    name: Loan Calculator
  mvc:
    format:
      date: yyyy-MM-dd
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    datasource-platform: org.hibernate.dialect.H2Dialect
